# EasyLogin | Made with love by Andretex and ThreeWhi

# If you're having problems contact me here: https://discord.gg/GbBT6hmAgY

############################################################
# +------------------------------------------------------+ #
# |                       Database                       | #
# +------------------------------------------------------+ #
############################################################
database:
  db-host: localhost         #MySQL ip Host
  db-port: 3306              #MySQL port
  db-database: easylogin     #Database for saving passwords
  db-username: root          #Database username
  db-password:               #Database password

  ############################################################
  # +------------------------------------------------------+ #
  # |                       Language                       | #
  # +------------------------------------------------------+ #
  ############################################################
messages:
  command:
    help: "&8&l[&eEasyLogin&8 \n  "
  help:
    noplayer: "You are not a player!"

############################################################
# +------------------------------------------------------+ #
# |                        Perms                         | #
# +------------------------------------------------------+ #
############################################################
commands:
  help:
    permission: