# EasyLogin | Made with love by Andretex and ThreeWhi

# If you're having problems contact me here: https://discord.gg/GbBT6hmAgY

############################################################
# +------------------------------------------------------+ #
# |                       Database                       | #
# +------------------------------------------------------+ #
############################################################
database:
  db-host: localhost         #MySQL ip Host
  db-port: 3306              #MySQL port
  db-database: easylogin     #Database for saving passwords
  db-username: root          #Database username
  db-password:               #Database password

  ############################################################
  # +------------------------------------------------------+ #
  # |                       Language                       | #
  # +------------------------------------------------------+ #
  ############################################################
messages:
  console:
    you-are-not-a-player: "You are not a Player"
  command:
    help: "\n
    #You can translate the comments of the command
    &c/easyhelp       &eShow all commands \n 
    &c/register       &eregister you account \n 
    &c/login          &eLogin to your account \n 
    &c/premium        &emake your account premium \n 
    &e/unregister     &cUnregister specific account
    "

############################################################
# +------------------------------------------------------+ #
# |                        Perms                         | #
# +------------------------------------------------------+ #
############################################################
commands:
  help:
    permission: #If there is nothing all players can do /easyhelp

  login:
    permission: #If there is nothing all players can do /login

  register:
    permission: #If there is nothing all players can do /register